services:
  vue-app-beta:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=beta.pawpy.fr
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=beta.pawpy.fr
      - LETSENCRYPT_EMAIL=contact@pawpy.fr
    networks:
      - web
    restart: unless-stopped

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-acme:

networks:
  web:
    external: true